version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: M@i$#100%
      MYSQL_DATABASE: plataforma
      MYSQL_USER: lcdias
      MYSQL_PASSWORD: M@i$#100%
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

    